### ISSUE TITLE
possible bug in function sample_true_false_edges_partial

### ISSUE THREAD

**Issue by Geutg** [hexie1995/TemporalOptimalLinkPrediction#1]
Hi Xie! 
I came across some code lines that i think might have a bug? could you give me your opinion on it?
its in file `TOLP.py` on lines 1782-1784
I also added a screenshot:
![sample_true_false_edges_partial](https://github.com/user-attachments/assets/f5b032d8-2c23-4766-b578-21c8e729295e)

considering the other places with similar code, shouldnt line 1784 be as such: 
`pos_edges = sparse.find(sparse.triu(A_diff,1)) # true candidates`
or am I mistaken? 
otherwise `A_diff` is never used inside this loop.

if it is as it should, can you tell me why?

Thanks,
Geut.

**Comment by hexie1995** [comment]
Hi Geut,

This is indeed a feature implemented because partial observation should be allowed to see the features from the training target layer as well, which is why the A_tr is directly used instead of using the A_diff, which is the one that should be used if we are considering the completely missing cases. If there's still confusion please let me know. 

Best,

Xie

**Comment by Geutg** [comment]
Ok! thank you for the explanation!
so lines 1782-1783 are unnecessary? are fine if deleted?

Best, 
Geut.

**Comment by hexie1995** [comment]
Yes, that would be fine, I will see to it to be updated as well!
Thank you for finding the issue! Please feel free to submit more if you
find anything or email me directly.

Best,

Xie
